### ISSUE TITLE
1.13 1:1000 creative map not working in spigot paper 1.13.2

### ISSUE THREAD

**Issue by Alex-DataSIM** [MattiBorchers/MinecraftEarthMap#3]
Didn't know where else to ask this, sorry that it isn't relevant to this git repo.

I'm having an issue where the map isn't generating like it should, its default minecraft terrain rather than custom earth shaped terrain.

Steps to reproduce:
Download the creative 1.13 map from http://earth.motfe.net.
Rename the map folder to 'earth'.
Import the map to the running spigot paper server using the multiverse plugin.
Using the dynmap plugin, render the world completely so that it can be seen online.

The result is a dynmap map with completely normal terrain (no earth shape at all).

Any help would be greatly appreciated.

**Comment by xCustomWorld** [comment]
Hello there!

I had issue like this too. I asked my friend to upload the map to the server directory, because it was too big. Result was the same. I'm using Paper 1.13.2 too, but let's move to the fix:

Create new, empty world with Multiverse (/mv create earth normal for example). 
When it's done, stop your server, go to the world directory and delete everything inside regions and also level.dat and data folder.
Then upload regions and data files from the actual earth map. My friend did it like this and it worked. I don't know how you uploaded and imported it, but I think that the problem is Multiverse: When new world is registered, the server attempts to get it's generator etc... But when some file is corrupted, it overrides the regions with default generator (level.dat is where generator is stored).

I don't know if this will help you, but this worked for me. If you need any more details, just contact me or reply there! 
Also, the full world is now rendered at customworld.craft
gg:40008, so you better check it if you want the world to look like this (currently fresh and 1:1000 scale).

**Comment by Alex-DataSIM** [comment]
> Hello there!
> 
> I had issue like this too. I asked my friend to upload the map to the server directory, because it was too big. Result was the same. I'm using Paper 1.13.2 too, but let's move to the fix:
> 
> Create new, empty world with Multiverse (/mv create earth normal for example).
> When it's done, stop your server, go to the world directory and delete everything inside regions and also level.dat and data folder.
> Then upload regions and data files from the actual earth map. My friend did it like this and it worked. I don't know how you uploaded and imported it, but I think that the problem is Multiverse: When new world is registered, the server attempts to get it's generator etc... But when some file is corrupted, it overrides the regions with default generator (level.dat is where generator is stored).
> 
> I don't know if this will help you, but this worked for me. If you need any more details, just contact me or reply there!
> Also, the full world is now rendered at customworld.craft
> gg:40008, so you better check it if you want the world to look like this (currently fresh and 1:1000 scale).
> 
> Edit: Yes, for some reasons, it overwrites the regions with default generator, I had problems with singleplayer world as well.)

Hey thanks for all the info.

I will test your solution tonight and let you know how it goes.

**Comment by Alex-DataSIM** [comment]
@xCustomWorld 
I didn't seem to work for me.

Here is what I did:
1) Start a fresh spigot paper 1.13.2 server with multiverse and worldborder installed.
2) /mv create test normal.
3) Close the server.
4) In test world directory, delete regions, level.dat and data.
5) Extract map earth_1-1000_1-13 from earth-1-1000_1-13_creative.zip
6) Move regions and level.dat from earth_1-1000_1-13 to test.
7) Start server
8) /mvtp test
9) I spawn in the middle of an ocean. 
10) At this point to the best of my knowledge the best way to see if its the right map is to tp to the northern part of the map and see if its all ice/snow.
11) /tp 0 100 -10749 - this tp's me to the centre of a jungle with the end of the map directly in-front of me.

Those are the exact steps I followed, I did nothing unless it was written above.
Am I doing anything differently compared to how your friend did it?

Also, is it mandatory to do a complete /wb fill before I see the actual shape of the world using this method?

Thanks again,
Alex

**Comment by xCustomWorld** [comment]
The spawn is in the middle of the ocean indeed. Try getting coordinates from [http://earth.motfe.net/map/index.html#1_1000_topdown/0/0/0/-64/64](this URL).

If you still don't see what you want to see (ex. if you teleport to some snowy mountains and you see a plains biome instead), I can troubleshoot it for you more. We should find how the error is caused first, perhaps...

**Comment by Alex-DataSIM** [comment]
@xCustomWorld Thanks for all the help, I managed to get the map working by rebuilding it on worldpainter. After I did that I just had to import it normally and everything worked.
