### ISSUE TITLE
Query about Iceland.

### ISSUE THREAD

**Issue by Quavelen** [MattiBorchers/MinecraftEarthMap#6]
So, um... a few months ago, I rendered a 1:1000 scale (**Edit:** *Oops, forgot a 0.*) version of your earth map for a friend to run his server on, and I just today realised your Iceland is covered in snow and ice lol. Is there any possibility I could suggest that you update this, to match the real-world Iceland?

Here are two examples, from Google Maps. One of the entire land mass, and one of my favourite town, Grundarfjörður, with its surrounding areas:

![unknown](https://user-images.githubusercontent.com/19168008/60925894-726b3980-a294-11e9-92bb-f507d5237aa9.png)

![unknown2](https://user-images.githubusercontent.com/19168008/60925843-4c459980-a294-11e9-8bd1-103ccfa58d4a.png)

Other than the icecaps on the tips of the mountains, Iceland is a lush, green land with lots of rich farmland. I'd really appreciate if if you could update it.

**Comment by MattiBorchers** [comment]
Hey, thanks for you message,

I know that not every point on the map is a perfect match to the real world. That's due to several points: First of all, I'm only using data instead of painting regions by hand to make them "look good". When you take a look at the "Köppen climate classification", you will see that Iceland is almost everywhere ET. (Quote: Tundra climates ordinarily fit the Köppen climate classification ET, signifying a local climate in which at least one month has an average temperature high enough to melt snow (0 °C (32 °F)), but no month with an average temperature in excess of 10 °C (50 °F).)

![climate](https://user-images.githubusercontent.com/47185281/60950670-dffc8180-a2f7-11e9-8c2d-26cf636574d4.png)

I had to match these classications to Minecraft Biomes (which are also not 100% comparable with real biomes) and the best for Tundra is... Minecraft's "Tundra". Sadly, this biome is completly covered with snow, which is not true in the real world, but that's something I can't change.

When using the "Globcover Data" you will get a lot of trouble, because most of the planet is either grass or sand and you can't use this to assign biomes.

![iceland_globecover](https://user-images.githubusercontent.com/47185281/60950674-e12dae80-a2f7-11e9-8252-6bf61183965a.jpg)

But you can take a look at "Serenes Season" Mod, which is available for Forge (sadly only for 1.12.2 at the moment). This mod features seasons in your Minecraft world, where snow melts in the summer and crops only grow in specific seasons. 

I know thats not a good solution, but I was thinking about this a lot and didn't find a good and consistent way to get this done.

**Comment by Quavelen** [comment]
Oh.... well, that explains a lot. Yeah, it's a rather cold region despite the greenery. Using server-side mods are definitely out of the question, as it's a "Paper" server running a number of plugins such as "mcMMO". It's also in 1.14.3, which yeah, would make that mod kinda useless. =/


I guess if it really comes down to it, I could just terraform it ingame myself. It would be a project to keep me busy. Thank you for your response, I appreciate it.
